"use strict";

const SW_VERSION = "16";
const CACHE_NAME = "bitaya-mast-v16-visual-acceptance";
const CACHE_PREFIX = "bitaya-mast-";
const BUNDLE_PARTS = Array.from({ length: 7 }, (_, index) => `./.upgrade/part${String(index).padStart(2, "0")}.txt`);
const CORE_ASSETS = [
  "./","./index.html","./manifest.webmanifest","./assets/pwa/icon.svg","./assets/pwa/maskable.svg",
  "./styles/stage2.css","./styles/stage3.css","./styles/stage4.css","./styles/stage5.css","./styles/stage6.css","./styles/stage7.css","./styles/stage8.css","./styles/stage9.css",
  "./styles/diegetic-ui.css","./styles/physical-card-interactions.css","./styles/scene-asset-assembly.css","./styles/visual-v2-integration.css","./styles/visual-v2-polish.css","./styles/visual-acceptance-console.css",
  "./compatibility-runtime.js","./src/core/storage-vault.js","./src/core/storage-vault-extension.js","./src/core/stage8-compat.js","./src/core/pwa-manager.js","./src/core/battle-engine.js","./src/core/timed-battle-engine.js","./src/core/timer-settings.js","./src/core/stage4-battle-engine.js","./src/core/stage4-runtime.js","./src/core/stage6-battle-runtime.js","./src/core/stage7-battle-runtime.js","./src/core/dealer-ai.js","./src/core/content-settings.js","./src/core/deck-view-model.js","./src/core/act-run-engine.js","./src/core/run-profile.js","./src/core/release-card-balance.js","./src/core/release-dealer-balance.js","./src/core/release-run-balance.js","./src/core/release-achievements.js","./src/core/release-audio.js",
  "./src/data/card-catalog.js","./src/data/dealer-catalog.js","./src/data/act1-content.js","./src/data/stage2-cards.js","./src/data/stage4-assets.js","./src/data/stage2-assets-scene.js","./src/data/stage2-assets-a.js","./src/data/stage2-assets-b.js","./src/data/scene-asset-manifest.js",
  "./src/ui/stage2-app.js","./src/ui/stage3-app.js","./src/ui/stage4-runtime.js","./src/ui/stage5-deck.js","./src/ui/stage6-app-loader.js","./src/ui/stage6-dealers.js","./src/ui/stage7-act.js","./src/ui/stage8-system.js","./src/ui/stage8-system-extension.js","./src/ui/stage9-release.js","./src/ui/stage3-initial-save-guard.js","./src/ui/scene-asset-assembler.js","./src/ui/physical-card-interactions.js","./src/ui/visual-v2-polish.js","./src/ui/visual-acceptance-console.js",
  "./assets/scene/v2/background.svg","./assets/scene/v2/table.svg","./assets/scene/v2/ambient.svg","./assets/scene/v2/dust.svg","./assets/scene/v2/vignette.svg","./assets/dealers/v2/dealer-atlas.svg","./assets/cards/v2/starter-sheet.svg"
];
const OPTIONAL_ASSETS = ["./legacy.html","./brand-runtime.js","./theme-enhancer.css","./theme-enhancer.js","./assets/theme/deck.svg","./assets/theme/hero.svg","./assets/theme/enemy.svg","./assets/theme/icon-attack.svg","./assets/theme/icon-skill.svg","./assets/theme/icon-power.svg","./assets/theme/node-battle.svg","./assets/theme/node-event.svg","./assets/theme/node-rest.svg","./assets/theme/node-elite.svg",...BUNDLE_PARTS];
async function fetchWithTimeout(request,timeoutMs){const controller=typeof AbortController==="function"?new AbortController():null;const timeout=controller?setTimeout(()=>controller.abort(),timeoutMs):null;try{return await fetch(request,controller?{signal:controller.signal,cache:"no-store"}:{cache:"no-store"});}finally{if(timeout)clearTimeout(timeout);}}
async function cacheOne(cache,url){try{const response=await fetch(new Request(url,{cache:"reload"}));if(response.ok)await cache.put(url,response.clone());return response.ok;}catch(error){return false;}}
async function installAssets(){const cache=await caches.open(CACHE_NAME);const coreResults=await Promise.all(CORE_ASSETS.map(url=>cacheOne(cache,url)));if(coreResults.some(result=>!result))throw new Error("Не удалось закэшировать ядро визуальной приёмки.");await Promise.allSettled(OPTIONAL_ASSETS.map(url=>cacheOne(cache,url)));if(!self.registration.active)await self.skipWaiting();}
async function removeOldCaches(){const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)));}
async function cacheMatch(request){return caches.match(request,{ignoreSearch:true});}
async function networkFirst(request,timeoutMs,fallbackUrl){try{const response=await fetchWithTimeout(request,timeoutMs);if(response&&response.ok){const cache=await caches.open(CACHE_NAME);cache.put(request,response.clone()).catch(()=>null);}return response;}catch(error){const cached=await cacheMatch(request);if(cached)return cached;if(fallbackUrl){const fallback=await cacheMatch(fallbackUrl);if(fallback)return fallback;}throw error;}}
async function staleWhileRevalidate(request){const cached=await cacheMatch(request);const update=fetch(request).then(async response=>{if(response&&response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone());}return response;}).catch(()=>null);if(cached){update.catch(()=>null);return cached;}return(await update)||Response.error();}
function isNavigation(request){if(request.mode==="navigate")return true;const url=new URL(request.url);return url.pathname.endsWith("/")||url.pathname.endsWith("/index.html")||url.pathname.endsWith("/legacy.html");}
function isVersionedCode(request){return /\.(?:js|css|html|webmanifest)$/.test(new URL(request.url).pathname);}
self.addEventListener("install",event=>{event.waitUntil(installAssets());});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{await removeOldCaches();if(self.registration.navigationPreload){try{await self.registration.navigationPreload.enable();}catch(error){}}await self.clients.claim();})());});
self.addEventListener("message",event=>{const message=event.data||{};if(message.type==="SKIP_WAITING")self.skipWaiting();if(message.type==="CLEAR_OLD_CACHES")event.waitUntil(removeOldCaches());if(message.type==="GET_VERSION"&&event.ports&&event.ports[0])event.ports[0].postMessage({version:SW_VERSION,cacheName:CACHE_NAME,release:"visual-acceptance",state:self.registration.active?"active":"waiting"});});
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(isNavigation(request)){event.respondWith((async()=>{try{const preload=await event.preloadResponse;if(preload)return preload;}catch(error){}return networkFirst(request,4500,"./index.html");})());return;}if(isVersionedCode(request)){event.respondWith(networkFirst(request,3500).then(response=>response||Response.error()).catch(async()=>(await cacheMatch(request))||Response.error()));return;}event.respondWith(staleWhileRevalidate(request));});